Repository intel-retail/automated-vending, pull requests merged in 2022-09, with the labels that each got.

#16 feat: upgrade ds-card-reader service to edgex 2.2
  docker-compose.ac.yml
  docs/automated-checkout-services/device_services.html
  docs/events.html
  docs/phases/phase1.html
  docs_src/automated-checkout-services/device_services.md
  docs_src/events.md
  docs_src/phases/phase1.md
  ds-card-reader/.gitignore
  ds-card-reader/.golangci.yml
  ds-card-reader/Dockerfile
  ds-card-reader/LICENSE
  ds-card-reader/Makefile
  ds-card-reader/common/common.go
  ds-card-reader/device/device.go
  ds-card-reader/device/physical.go
  ds-card-reader/device/physical_test.go
  ds-card-reader/device/virtual.go
  ds-card-reader/device/virtual_test.go
  ds-card-reader/driver/driver.go
  ds-card-reader/driver/driver_test.go
  ds-card-reader/go.mod
  ds-card-reader/go.sum
  ds-card-reader/main.go
  ds-card-reader/res/configuration.toml
  ds-card-reader/res/devices/device-list.toml
  ds-card-reader/res/ds-card-reader.yaml
  ds-card-reader/res/profiles/ds-card-reader.yaml
Labels: documentation, enhancement

#19 docs: updated Ubuntu version to 20.04
  docs/index.html
  docs_src/index.md
Labels: documentation

#29 feat: Added custom config to ds-card-reader
  ds-card-reader/common/common.go
  ds-card-reader/device/config.go
  ds-card-reader/device/config_test.go
  ds-card-reader/device/physical.go
  ds-card-reader/device/virtual_test.go
  ds-card-reader/driver/driver.go
  ds-card-reader/driver/driver_test.go
  ds-card-reader/go.mod
  ds-card-reader/go.sum
  ds-card-reader/res/configuration.toml
Labels: enhancement

#27 feat: added AppCustom configuration to ds-controller-board
  ds-controller-board/device/common.go
  ds-controller-board/device/common_test.go
  ds-controller-board/device/config.go
  ds-controller-board/device/config_test.go
  ds-controller-board/driver/driver.go
  ds-controller-board/driver/driver_test.go
  ds-controller-board/go.mod
  ds-controller-board/go.sum
  ds-controller-board/main.go
  ds-controller-board/res/configuration.toml
Labels: enhancement

#31 fix: refactor ms-authentication to use logging client to log errors/info
  ms-authentication/go.mod
  ms-authentication/main.go
  ms-authentication/routes/controller.go
  ms-authentication/routes/controller_test.go
  ms-authentication/routes/gets.go
  ms-authentication/routes/gets_test.go
Labels: enhancement

#32 feat: using CommandClient
  as-vending/functions/models.go
  as-vending/functions/output.go
  as-vending/functions/output_test.go
  as-vending/go.mod
  as-vending/main.go
  as-vending/res/configuration.toml
  docker-compose.ac.yml
Labels: enhancement

#30 fix: refactor ms-inventory to use logging client to log errors/info
  ms-inventory/go.mod
  ms-inventory/main.go
  ms-inventory/routes/common.go
  ms-inventory/routes/common_test.go
  ms-inventory/routes/controller.go
  ms-inventory/routes/controller_test.go
  ms-inventory/routes/deletes.go
  ms-inventory/routes/deletes_test.go
  ms-inventory/routes/gets.go
  ms-inventory/routes/gets_test.go
  ms-inventory/routes/sets.go
  ms-inventory/routes/sets_test.go
Labels: enhancement
