Repository intel-retail/automated-vending, pull requests merged in 2023-09, with the labels that each got.

#120 fix: Correct link and wording in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#139 feat: Migrate as-vending microservice to EdgeX 3.0
  .github/workflows/trivyimagescan.yaml
  as-vending/Dockerfile
  as-vending/Makefile
  as-vending/functions/models.go
  as-vending/functions/output.go
  as-vending/functions/output_test.go
  as-vending/go.mod
  as-vending/go.sum
  as-vending/main.go
  as-vending/res/configuration.toml
  as-vending/res/configuration.yaml
  as-vending/routes/controller.go
  as-vending/routes/controller_test.go
  docker-compose.ac.yml
Labels: enhancement

#141 feat: Migrate ms-ledger microservice to EdgeX 3.0
  .github/workflows/trivyimagescan.yaml
  docker-compose.ac.yml
  ms-ledger/Dockerfile
  ms-ledger/Makefile
  ms-ledger/go.mod
  ms-ledger/go.sum
  ms-ledger/main.go
  ms-ledger/res/configuration.toml
  ms-ledger/res/configuration.yaml
  ms-ledger/routes/common_test.go
  ms-ledger/routes/controller.go
  ms-ledger/routes/controller_test.go
  ms-ledger/routes/deletes_test.go
  ms-ledger/routes/gets_test.go
  ms-ledger/routes/sets_test.go
Labels: enhancement

#145 feat: Migrate ds-controller microservice to EdgeX 3.0
  .github/workflows/trivyimagescan.yaml
  docker-compose.ac.yml
  ds-controller-board/.golangci.yml
  ds-controller-board/Dockerfile
  ds-controller-board/Makefile
  ds-controller-board/device/common.go
  ds-controller-board/device/common_test.go
  ds-controller-board/device/config.go
  ds-controller-board/device/config_test.go
  ds-controller-board/device/device.go
  ds-controller-board/device/device_test.go
  ds-controller-board/device/mocks/ControllerBoard.go
  ds-controller-board/device/physical.go
  ds-controller-board/device/physical_test.go
  ds-controller-board/device/virtual.go
  ds-controller-board/device/virtual_test.go
  ds-controller-board/driver/driver.go
  ds-controller-board/driver/driver_test.go
  ds-controller-board/go.mod
  ds-controller-board/go.sum
  ds-controller-board/main.go
  ds-controller-board/res/configuration.toml
  ds-controller-board/res/configuration.yaml
  ds-controller-board/res/devices/device-list.toml
  ds-controller-board/res/devices/device-list.yaml
  ds-controller-board/res/profiles/ds-controller-board.yaml
Labels: enhancement

#146 build: Upgrade portianer to CE version
  docker-compose.portainer.yml
Labels: dependencies

#148 fix: Address Lenny's PR comments
  ds-cv-inference/mqtt/mqtt.go
Labels: enhancement

#154 feat: Update test script for v3 endpoints
  smoke-test.sh
Labels: enhancement

#155 refactor: Fix naming of checkout-> vending and fix service names
  Makefile
  docker-compose.av.yml
Labels: enhancement

#151 refactor: Use command client for as-controller-board-status to send commands instead of using REST calls.
  as-controller-board-status/config/configuration.go
  as-controller-board-status/functions/common_test.go
  as-controller-board-status/functions/models.go
  as-controller-board-status/functions/output.go
  as-controller-board-status/functions/output_test.go
  as-controller-board-status/main.go
  as-controller-board-status/res/configuration.yaml
  as-vending/functions/output.go
Labels: enhancement

#152 feat: update docs for edgex 3.0 update
  docs_src/automated-vending-services/application_services.md
  docs_src/automated-vending-services/device_services.md
  docs_src/automated-vending-services/micro_services.md
  docs_src/configuration.md
  docs_src/events.md
  docs_src/images/automated-vending-reference-implementation.png
  docs_src/images/automated-vending.png
  docs_src/index.md
  docs_src/modifying_source_code.md
  docs_src/phases/phase1.md
  docs_src/phases/phase2.md
  docs_src/phases/phase3.md
  docs_src/references.md
  docs_src/troubleshooting.md
  mkdocs.yml
Labels: documentation, enhancement
